import { appendCrc, validRtuFrame } from "../utils/modbusRtu";
import type { MemoryState, RegisterBank, Tag } from "../types";
interface WorkerServer { id: string; memory: MemoryState; socket?: WebSocket; tags: Tag[]; }
const servers = new Map<string, WorkerServer>(); let loggingActive = false;
const makeMemory = (): MemoryState => ({ coils: new Array(10000).fill(false), discreteInputs: new Array(10000).fill(false), holdingRegisters: new Array(10000).fill(0), inputRegisters: new Array(10000).fill(0) });
const emit = (data: unknown) => postMessage(data);
const log = (serverId: string, direction: "tx" | "rx" | "error", bytes: Uint8Array, description: string) => { if (loggingActive) emit({ type: "LOG", entry: { id: crypto.randomUUID(), timestamp: new Date().toISOString(), serverId, direction, rawBytes: Array.from(bytes.slice(0, 32)), description } }); };
const getServer = (id: string): WorkerServer => { let server = servers.get(id); if (!server) { server = { id, memory: makeMemory(), tags: [] }; servers.set(id, server); } return server; };
const bankForFunction = (fc: number): RegisterBank => fc === 1 ? "coils" : fc === 2 ? "discreteInputs" : fc === 4 ? "inputRegisters" : "holdingRegisters";
const readValues = (server: WorkerServer, bank: RegisterBank, address: number, quantity: number): number[] => { if (address < 0 || quantity < 1 || address + quantity > 10000) throw new Error("Address range outside simulator memory"); return server.memory[bank].slice(address, address + quantity) as number[]; };
function tcpResponse(server: WorkerServer, request: Uint8Array): Uint8Array { if (request.length < 12 || request[2] !== 0 || request[3] !== 0) throw new Error("Invalid MBAP header"); const transaction = request.slice(0, 2); const unit = request[6]; const fc = request[7]; const address = (request[8] << 8) | request[9]; const quantity = (request[10] << 8) | request[11]; if (![1, 2, 3, 4].includes(fc) || quantity < 1 || quantity > (fc <= 2 ? 2000 : 125)) throw new Error("Invalid Modbus TCP request"); const values = readValues(server, bankForFunction(fc), address, quantity); const payload = new Uint8Array(3 + (fc <= 2 ? Math.ceil(quantity / 8) : quantity * 2)); payload[0] = unit; payload[1] = fc; payload[2] = payload.length - 3; values.forEach((value, index) => fc <= 2 ? (value && (payload[3 + Math.floor(index / 8)] |= 1 << (index % 8))) : (payload[3 + index * 2] = value >>> 8, payload[4 + index * 2] = value & 255)); const response = new Uint8Array(6 + payload.length); response.set(transaction); response[4] = payload.length >>> 8; response[5] = payload.length; response.set(payload, 6); return response; }
function rtuResponse(server: WorkerServer, request: Uint8Array): Uint8Array { if (!validRtuFrame(request) || request.length < 8) throw new Error("Invalid RTU CRC or frame"); const fc = request[1]; const address = (request[2] << 8) | request[3]; const quantity = (request[4] << 8) | request[5]; const values = readValues(server, bankForFunction(fc), address, quantity); const response = new Uint8Array(3 + values.length * 2); response[0] = request[0]; response[1] = fc; response[2] = values.length * 2; values.forEach((value, index) => { response[3 + index * 2] = value >>> 8; response[4 + index * 2] = value & 255; }); return appendCrc(response); }
function tick(): void { for (const server of servers.values()) for (const tag of server.tags) { if (tag.simMode === "constant") continue; const time = Date.now() / 1000; const value = tag.simMode === "sine" ? 100 + Math.sin(time) * 50 : tag.simMode === "ramp" ? Math.floor(time) % 100 : 90 + Math.random() * 20; server.memory[tag.regBank][tag.modbusAddress] = Math.round(value); emit({ type: "MEMORY", serverId: server.id, bank: tag.regBank, address: tag.modbusAddress, value: Math.round(value), tagId: tag.id, tagValue: value }); } }
onmessage = ({ data }) => { try { if (data.type === "INIT_TAGS") { const grouped = new Map<string, Tag[]>(); for (const tag of data.tags as Tag[]) grouped.set(tag.serverId, [...(grouped.get(tag.serverId) || []), tag]); for (const [id, tags] of grouped) { const server = getServer(id); server.tags = tags; tags.forEach(tag => { server.memory[tag.regBank][tag.modbusAddress] = tag.value; }); } } else if (data.type === "CONNECT_TCP") { const server = getServer(data.serverId); server.socket = new WebSocket(`ws://${data.host}:${data.port}`); server.socket.binaryType = "arraybuffer"; server.socket.onopen = () => emit({ type: "STATUS", serverId: data.serverId, status: "connected" }); server.socket.onclose = () => emit({ type: "STATUS", serverId: data.serverId, status: "disconnected" }); server.socket.onerror = () => emit({ type: "STATUS", serverId: data.serverId, status: "error", error: "WebSocket connection failed" }); server.socket.onmessage = event => { const request = new Uint8Array(event.data); log(server.id, "rx", request, "Modbus TCP request"); const response = tcpResponse(server, request); log(server.id, "tx", response, "Modbus TCP response"); server.socket?.send(response); }; emit({ type: "STATUS", serverId: data.serverId, status: "connecting" }); } else if (data.type === "PROCESS_RTU") emit({ type: "RTU_RESPONSE", serverId: data.serverId, bytes: Array.from(rtuResponse(getServer(data.serverId), new Uint8Array(data.bytes))) }); else if (data.type === "DISCONNECT" || data.type === "REMOVE_SERVER") { servers.get(data.serverId)?.socket?.close(); servers.delete(data.serverId); } else if (data.type === "SET_LOGGING_ACTIVE") loggingActive = Boolean(data.active); else if (data.type === "WRITE") getServer(data.serverId).memory[data.bank as RegisterBank][data.address] = data.value; else if (data.type === "STOP") { servers.forEach(server => server.socket?.close()); servers.clear(); } } catch (error) { emit({ type: "LOG", entry: { id: crypto.randomUUID(), timestamp: new Date().toISOString(), serverId: data.serverId || "system", direction: "error", rawBytes: [], description: error instanceof Error ? error.message : "Worker error" } }); } };
setInterval(tick, 500);
