import type { Tag } from "../types";
import { bankFromDigit } from "./tagDatabase";
const wordsByType: Record<number, number> = { 1: 1, 2: 2, 3: 1, 4: 2, 5: 2, 6: 4, 7: 1, 8: 2, 9: 1, 10: 2, 11: 2, 12: 4, 13: 1, 14: 1 };
const names: Record<number, string> = { 1: "Int16 Input", 2: "Int32 Input", 3: "UInt16 Input", 4: "UInt32 Input", 5: "Float32 Input", 6: "Float64 Input", 7: "Int16 Output", 8: "Int32 Output", 9: "UInt16 Output", 10: "UInt32 Output", 11: "Float32 Output", 12: "Float64 Output", 13: "Discrete Input", 14: "Discrete Output" };
const cells = (line: string) => line.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(value => value.trim().replace(/^\"|\"$/g, ""));
export function parseCsv(source: string): { tags: Tag[]; errors: string[] } {
  const lines = source.split(/\r?\n/).filter(Boolean); if (lines.length < 5) return { tags: [], errors: ["CSV must contain four metadata rows and a header row."] };
  const headers = cells(lines[4]); const column = (name: string) => headers.findIndex(header => header.toLowerCase() === name.toLowerCase());
  const required = ["@Element", "Buffer", "Program Name", "Size", "Port", "IP Address", "Station", "Device&Address", "Data Type", "Reverse", "Scan", "Service Comment", "Label"]; const missing = required.filter(name => column(name) < 0); if (missing.length) return { tags: [], errors: [`Missing columns: ${missing.join(", ")}`] };
  const get = (row: string[], name: string) => row[column(name)] || ""; const tags: Tag[] = []; const hostPorts = new Map<string, number>(); let nextPort = 5020; let current: Partial<Tag> = {};
  lines.slice(5).forEach((line, rowIndex) => { const row = cells(line); const programName = get(row, "Program Name"); if (!/MODBUS/i.test(programName)) return; const device = get(row, "Device&Address"); if (device && device !== "*") { const match = device.match(/^([A-Z])D([0134])(\d{1,5})$/i); if (!match) return; const typeCode = Number(get(row, "Data Type")) || 1; const ip = get(row, "IP Address"); const isRtu = !ip; const port = get(row, "Port") || "1"; const assignedPort = hostPorts.get(ip) || nextPort++; if (!isRtu) hostPorts.set(ip, assignedPort); current = { serverId: isRtu ? `RTU-${programName}-${port}` : `${ip}:${assignedPort}`, ipAddress: ip || undefined, isRtu, nsp: `${programName.replace(/^K1-/, "").replace(/[^0-9-].*$/, "")}-${Number(port)}`, deviceAddress: device, updateMode: match[1].toUpperCase(), regBank: bankFromDigit(match[2]), modbusAddress: Number(match[3]), dataTypeCode: typeCode, dataTypeName: names[typeCode] || "UInt16", wordSize: wordsByType[typeCode] || 1, reverseSwap: Number(get(row, "Reverse")) || 3, programName, station: get(row, "Station"), port, buffer: get(row, "Buffer"), size: get(row, "Size"), scan: get(row, "Scan") }; } if (!current.serverId || !current.regBank) return; const element = get(row, "@Element") || `%WW${String(current.modbusAddress || 0).padStart(4, "0")}`; tags.push({ ...current, id: `${current.serverId}-${element}-${rowIndex}`, label: get(row, "Label") || `TAG_${rowIndex + 1}`, comment: get(row, "Service Comment"), element, value: current.dataTypeCode && current.dataTypeCode >= 13 ? 1 : 100, simMode: "constant" } as Tag); });
  return { tags, errors: [] };
}
export function formatRange(value: number, words: number): string { const start = String(value).padStart(4, "0"); return words > 1 ? `${start}-${String(value + words - 1).padStart(4, "0")}` : start; }
export function sortTags(tags: Tag[]): Tag[] { return [...tags].sort((a, b) => a.serverId.localeCompare(b.serverId, undefined, { numeric: true }) || a.modbusAddress - b.modbusAddress); }
