import { ModbusTag } from "../types";
import { formatElementRange, formatDeviceAddrRange, extractNsp } from "./csvTagParser";

/**
 * Default Factory Yokogawa ALE111 Tag Definitions
 * Pre-configured industrial tags for CENTUM VP Modbus Station simulation.
 */
const RAW_FACTORY_TAGS: any[] = [
  {
    id: "ale111-001",
    label: "FIC101.PV",
    comment: "Crude Feed Flow Rate Control - Process Value",
    element: "%WW0001",
    deviceAddress: "A40001",
    updateMode: "A",
    regBank: "holdingRegisters",
    modbusAddress: 0,
    dataTypeCode: 5,
    dataTypeName: "Input (32-Bit Floating)",
    wordSize: 2,
    reverseSwap: 2,
    value: 142.8,
    simMode: "sine",
    programName: "K1-1-1MOD",
    ipAddress: "172.31.28.101",
    station: "1",
    port: "1",
    buffer: "128",
    size: "16",
    scan: "1s"
  },
  {
    id: "ale111-002",
    label: "FIC101.SV",
    comment: "Crude Feed Flow Rate Control - Setpoint Value",
    element: "%WW0003",
    deviceAddress: "A40003",
    updateMode: "A",
    regBank: "holdingRegisters",
    modbusAddress: 2,
    dataTypeCode: 11,
    dataTypeName: "Output (32-Bit Floating)",
    wordSize: 2,
    reverseSwap: 2,
    value: 150.0,
    simMode: "constant",
    programName: "K1-1-1MOD",
    ipAddress: "172.31.28.101",
    station: "1",
    port: "1",
    buffer: "128",
    size: "16",
    scan: "1s"
  },
  {
    id: "ale111-003",
    label: "TIC202.PV",
    comment: "Distillation Column Top Temp - Process Value",
    element: "%WW0005",
    deviceAddress: "A40005",
    updateMode: "A",
    regBank: "holdingRegisters",
    modbusAddress: 4,
    dataTypeCode: 5,
    dataTypeName: "Input (32-Bit Floating)",
    wordSize: 2,
    reverseSwap: 2,
    value: 84.5,
    simMode: "sine",
    programName: "K1-1-1MOD",
    ipAddress: "172.31.28.101",
    station: "1",
    port: "1",
    buffer: "128",
    size: "16",
    scan: "1s"
  },
  {
    id: "ale111-004",
    label: "PIC303.PV",
    comment: "Reactor Overhead Pressure - Process Value",
    element: "%WW0007",
    deviceAddress: "A40007",
    updateMode: "A",
    regBank: "holdingRegisters",
    modbusAddress: 6,
    dataTypeCode: 5,
    dataTypeName: "Input (32-Bit Floating)",
    wordSize: 2,
    reverseSwap: 2,
    value: 3.42,
    simMode: "noise",
    programName: "K1-1-1MOD",
    ipAddress: "172.31.28.101",
    station: "1",
    port: "1",
    buffer: "128",
    size: "16",
    scan: "1s"
  },
  {
    id: "ale111-005",
    label: "LIC404.PV",
    comment: "Separator Drum Liquid Level - Process Value",
    element: "%WW0009",
    deviceAddress: "A40009",
    updateMode: "A",
    regBank: "holdingRegisters",
    modbusAddress: 8,
    dataTypeCode: 5,
    dataTypeName: "Input (32-Bit Floating)",
    wordSize: 2,
    reverseSwap: 2,
    value: 65.2,
    simMode: "ramp",
    programName: "K1-1-1MOD",
    ipAddress: "172.31.28.101",
    station: "1",
    port: "1",
    buffer: "128",
    size: "16",
    scan: "1s"
  },
  {
    id: "ale111-006",
    label: "XV501.CMD",
    comment: "Emergency Isolation Valve 501 Command Status",
    element: "%WW0011",
    deviceAddress: "B40011",
    updateMode: "B",
    regBank: "holdingRegisters",
    modbusAddress: 10,
    dataTypeCode: 14,
    dataTypeName: "Output (Discrete)",
    wordSize: 1,
    reverseSwap: 2,
    value: 1,
    simMode: "constant",
    programName: "K1-1-1MOD",
    ipAddress: "172.31.28.101",
    station: "1",
    port: "1",
    buffer: "128",
    size: "16",
    scan: "1s"
  },
  {
    id: "ale111-007",
    label: "PMP601.STAT",
    comment: "Main Boiler Feedwater Pump 601 Running Status",
    element: "%WW0012",
    deviceAddress: "B40012",
    updateMode: "B",
    regBank: "holdingRegisters",
    modbusAddress: 11,
    dataTypeCode: 13,
    dataTypeName: "Input (Discrete)",
    wordSize: 1,
    reverseSwap: 2,
    value: 1,
    simMode: "constant",
    programName: "K1-1-1MOD",
    ipAddress: "172.31.28.101",
    station: "1",
    port: "1",
    buffer: "128",
    size: "16",
    scan: "1s"
  },
  {
    id: "ale111-008",
    label: "GI701.VAL",
    comment: "Combustible Gas Analyzer Tag - Percent LEL",
    element: "%WW0013",
    deviceAddress: "A30001",
    updateMode: "A",
    regBank: "inputRegisters",
    modbusAddress: 0,
    dataTypeCode: 3,
    dataTypeName: "Input (16-Bit Unsigned)",
    wordSize: 1,
    reverseSwap: 2,
    value: 12,
    simMode: "noise",
    programName: "K1-1-1MOD",
    ipAddress: "172.31.28.101",
    station: "1",
    port: "1",
    buffer: "64",
    size: "8",
    scan: "1s"
  }
];

export const FACTORY_ALE111_TAGS: ModbusTag[] = RAW_FACTORY_TAGS.map(t => {
  const isRtu = !t.ipAddress || t.ipAddress.trim() === "";
  const nsp = extractNsp(t.programName, t.port);
  return {
    ...t,
    element: formatElementRange(t.element, t.wordSize),
    deviceAddress: formatDeviceAddrRange(t.deviceAddress, t.wordSize),
    serverId: isRtu ? `RTU-${nsp}` : `${t.ipAddress}:5020`,
    nsp,
    isRtu
  };
});
